### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ryan-lp** [Podcastindex-org/podping-hivewatcher#1]
This repository is missing a LICENSE file. I assume it was intended to be MIT like [podping.cloud](https://github.com/Podcastindex-org/podping.cloud/blob/main/LICENSE)

**Comment by daveajones** [comment]
@brianoflondon or @agates Do you have an opinion here?

**Comment by brianoflondon** [comment]
Whatever you have used for the rest of Podcasting 2.0 suits me, MIT I think?
